services:
  postgres:
    image: postgres:latest
    container_name: lab-2-tools-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - configuration-service-network
  
  configuration-service:
    image: ghcr.io/is-csms-y26/lab-2-tools:master
    platform: linux/amd64
    container_name: configuration-service
    networks:
      - configuration-service-network
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    environment:
      Persistence__Postgres__Host: postgres
      
  postgres-second:
    image: postgres:latest
    container_name: lab-2-task-3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - configuration-service-network

networks:
  configuration-service-network:
    driver: bridge